### ISSUE TITLE
Upload it on the Unity Asset Store

### ISSUE THREAD

**Issue by yvan-sraka** [playdeadgames/temporal#12]
Why not make this project available for free on [Unity Asset Store](https://www.assetstore.unity3d.com/)?

This could potentially give more visibility to the temporal AA, so more testers and potential contributors to this open source project!

**Comment by yvan-sraka** [comment]
I see that it is already part of the **Legacy Cinematic Image Effects**:

- https://www.assetstore.unity3d.com/en/#!/content/51515
- https://blogs.unity3d.com/2015/12/10/cinematic-image-effects-pre-release/
- https://bitbucket.org/Unity-Technologies/cinematic-image-effects

**Comment by pointcache** [comment]
This is a different implementation of TAA.

**Comment by yvan-sraka** [comment]
You're absolutely right!

**Comment by pointcache** [comment]
I am currently using https://www.assetstore.unity3d.com/en/#!/content/83912

**Comment by yvan-sraka** [comment]
So I can put it freely in the [Unity Assets Store](https://unity3d.com/asset-store/sell-assets) if PlayDead sees no problem ...

**Comment by Tanshaydar** [comment]
@yvan-sraka PlayDead is more than capable of putting their assets on Asset Store if they deemed necessary. Taking on such a task without their consent would not be nice.

**Comment by yvan-sraka** [comment]
You are certainly right! Maybe I feel a bit frustrated by the fact that PlayDead does not spend so much time answering to community requets on this Github project ...

**Comment by Tanshaydar** [comment]
It may be because they are working on a new game :)

**Comment by Xerxes1138** [comment]
Hi, I agree with the fact that is not good idea to put it the asset store unless you have their permission and yeah they must be very busy these days :)

**Comment by yvan-sraka** [comment]
You're right! You're right :D !

**Comment by petersvp** [comment]
There are people like me that PREFER github over the Asset Store. 
On Asset Store everything must be perfect, according to the TOS. I don't want to. On GitHub it's up to me. 

This TAA implementation is very well looking, but there are caveats and even bugs that are unused actually. On Asset Store, nobody likes bugs and I always manage to find a lot of bugs in all assets I purchase, including TextMesh Pro :)
