### ISSUE TITLE
2017.1

### ISSUE THREAD

**Issue by jazznazz** [playdeadgames/temporal#18]
Hi,
I really like this TAA implementation, Unity's own is not on so pretty. Thank You so much for it, good work! 

I dont't know if you guys have plans for supporting 2017.1 / 2 ? Right now, there are error messages when I try to use it on 2017.1, hope it helps: 

Shader error in 'Playdead/Post/VelocityBuffer': failed to open source file: 'IncDepth.cginc' at line 18 (on d3d11)
Compiling Vertex program with CAMERA_PERSPECTIVE TILESIZE_20
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_HARDWARE_TIER3

------------------------------------------------------

Shader error in 'Playdead/Post/TemporalReprojection': failed to open source file: 'IncDepth.cginc' at line 34 (on d3d11)

Compiling Vertex program with CAMERA_PERSPECTIVE MINMAX_3X3_ROUNDED UNJITTER_COLORSAMPLES USE_CLIPPING USE_DILATION USE_MOTION_BLUR USE_OPTIMIZATIONS
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_HARDWARE_TIER3

Thank You again, keep up the good work !

**Comment by eobet** [comment]
That's not an error related to this TAA solution, that's a general Unity quirk.

Just right click on the script in your assets and choose "Reimport" and the issue should go away.

(It will come back, though, until Unity fixes whatever underlying flaw that keeps spamming those all the time.)

**Comment by Invertex** [comment]
The problem is that Unity simply loads each of the files sequentially, so if the shader is imported before the .cginc file, the AssetDatabase has no record of that .cginc file and thus fails to load it, requiring reimporting again once they're registered. They really should implement some sort of (if doesn't exist in DB, search for actual file) when importing shaders.
