### ISSUE TITLE
Pass access error when running demo scene

### ISSUE THREAD

**Issue by aandnota** [playdeadgames/temporal#2]
I get this error when I run the demo scene:

```
Trying to access pass 1, but material 'Playdead/Post/VelocityBuffer' subshader (0) has only 1 valid passes.
UnityEngine.Material:SetPass(Int32)
```

I've edited the shader files to account for glcore.

Unity 5.4.3f1 on OSX 10.11.3

**Comment by yvan-sraka** [comment]
Hello,

Looks like this issue is a duplicate of: https://github.com/playdeadgames/temporal/issues/1
