### ISSUE TITLE
Ghosting Artifacts

### ISSUE THREAD

**Issue by robotron2084** [playdeadgames/temporal#3]
After applying the fix mentioned in #1(thanks!) it seems there is a bit of shimmering on the Example scene. I have attempted to create a gif to best show it:

![temporal_aa_artifacts](https://cloud.githubusercontent.com/assets/283968/14125528/8c59fdf6-f5c0-11e5-9c73-e1b5c13e81be.gif)

To repro:
Apply the fix mentioned in #1.
Open the Example scene.
Apply a rotation animation to cube 13.
Observe that below the cube a strange shimmering displays (not the shadow but directly down from the image).

**Comment by sfarmer1** [comment]
And this issue only seems to crop up with tagged objects. It is especially bad with objects tagged as skinned meshes.

**Comment by uzimonkey** [comment]
I also saw this on a skinned mesh renderer.  I can't reproduce it though.

**Comment by dmnddst** [comment]
It looks like one of the buffers is getting flipped (in OpenGL)

![flipped](https://cloud.githubusercontent.com/assets/7060022/14958916/4114e532-104a-11e6-9444-b2a463a394cb.jpg)
