### ISSUE TITLE
Does this AA solution work for orthographic cameras?

### ISSUE THREAD

**Issue by Hyperparticle** [playdeadgames/temporal#4]
Thanks for this fantastic AA solution!

I have tried to use this for orthographic cameras, but it appears to do nothing until I switch it to perspective. I may have missed something in the documentation, but I haven't seen anything that clearly specifies what camera types are supported.

Is this only limited to perspective cameras, or am I doing something wrong with orthographic?

**Comment by Sleem81** [comment]
Yeah I have the same problem

**Comment by yvan-sraka** [comment]
Yes, currently jittering and AA are enabled only if `camera.orthographic == false`.

So I just started working on this, I deleted the check, created another projection function for the orthographic camera. Now it just lacks the correct 4x4 matrix, I have copy-pasted the one used by the perspective projection, so if you activate the Frustum Jitter... SURPRISE: it switch to perspective view!

You can follow my changes here: https://github.com/yvan-sraka/temporal/commit/19ba3783302a83d124872cc0d56b8a6b49b5da57
