### ISSUE TITLE
VR support

### ISSUE THREAD

**Issue by MarcinRNowak** [playdeadgames/temporal#6]
Hi,

current version doesn't work properly with built-in VR camera. 
One problem is, that native Unity VR uses one virtual camera and then modifies it on the fly just before rendering.
Because of that one history buffer is used for both eyes, which obviously can't work (it appears as horizontal blur on both images).
Another problem is, that I can't get real camera position, which is needed by this effects. I have tried making 2 cameras, setting each for left or right eye, but it doesn't help. (I think camera parameters read by the script are still incorrect).

Any suggestion how to fix it would b greatly appreciated! :)

Cheers,
Marcin

**Comment by TheMasonX** [comment]
Hey there, if you're ever having problems with an image effect not working in VR, 'UnityStereoScreenSpaceUVAdjust(float2 uv, float4 , texture's ST variable). I've had a lot of luck getting this to work so far with every effect I've tried it on. Hope you already figured that out, but either way, have a great day!

**Comment by itszander** [comment]
Hey all, i'm trying to get TAA to work in VR as well. I'm a total newbie when it comes to this, but im wondering what you need to modify and how in order to make TAA work. I see everything working in the editor but the effect doesnt seem to work on device.

**Comment by Invertex** [comment]
I've created an updated version that should improve general 5.4+ usage, also some changes that should help with VR, but I cannot currently test it in VR, so any feedback would be great. Download it from my fork:
https://github.com/Invertex/temporal

**Comment by itszander** [comment]
Hi there, this looks great. I'll test it for sure.  Im wondering how we can fix the jitter that happens with a stationary camera.  On some objects far away we're seeing a little bit of this horizontal jitter. Is it normal?
