### ISSUE TITLE
Ghosts with velocity buffers

### ISSUE THREAD

**Issue by ec-ecss** [playdeadgames/temporal#9]
Hello,
I don't know if this fantastic work is intended to survive new versions on Unity, but I've got some "ghosts" (really, it looks like ghosts) of objects that have velocity buffer tags, in other places in the scene.
I be glad to show you some screenshots if you need it.
Bye

**Comment by yvan-sraka** [comment]
Hello,
Yes, this could help to send some screenshot plus some gist or repository of your Unity project to help replicate your issue!

**Comment by ec-ecss** [comment]
Hey there, here is the ghost effect on a video. 
https://drive.google.com/file/d/0BxNsf8S5n1YsZ3NCZnpFM3VwQTQ/view?usp=sharing
 You can see the artefact on the top wall. When I disable the velocity buffer tag on the main character, this problem disapears.
This is not obvious in this video, but the artefact is a sort of blured stain replicate of the main character.
My project is currently uselessly big and on draft , I can't share it to you as it,  I need to work to extract an little branch to reproduce the issue.
